"""Writes the dashboard.html file. Everything is inside the one file - no internet needed to view it."""

import json

TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Corporate Announcements &mdash; NSE &amp; BSE</title>
<style>
  :root{
    --bg:#f6f7f9; --card:#fff; --ink:#12161c; --muted:#606a78; --line:#e2e6ec;
    --accent:#1f6feb; --chip:#eef1f5; --pos:#0f7b3f; --posbg:#e6f5ec;
    --neg:#b3261e; --negbg:#fdeceb; --neu:#5a6472; --neubg:#eef1f5;
  }
  @media (prefers-color-scheme: dark){
    :root{
      --bg:#0e1116; --card:#161b22; --ink:#e6edf3; --muted:#9198a1; --line:#262c36;
      --accent:#589bff; --chip:#20262f; --pos:#5ddb96; --posbg:#0f2a1c;
      --neg:#ff8b82; --negbg:#2c1414; --neu:#9198a1; --neubg:#20262f;
    }
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);
       font:15px/1.5 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
  .wrap{max-width:1080px;margin:0 auto;padding:24px 18px 64px}
  header h1{font-size:23px;margin:0 0 4px;letter-spacing:-.02em}
  header p{margin:0;color:var(--muted);font-size:13.5px}

  .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(92px,1fr));
         gap:10px;margin:18px 0 14px}
  .stat{background:var(--card);border:1px solid var(--line);border-radius:10px;
        padding:9px 14px}
  .stat b{display:block;font-size:19px;letter-spacing:-.01em}
  .stat span{color:var(--muted);font-size:11.5px;text-transform:uppercase;letter-spacing:.05em}

  .controls{position:sticky;top:0;background:var(--bg);padding:10px 0 12px;z-index:5;
            border-bottom:1px solid var(--line);margin-bottom:16px}
  input[type=search]{width:100%;padding:10px 12px;border:1px solid var(--line);
        border-radius:9px;background:var(--card);color:var(--ink);font-size:14px;margin-bottom:9px}
  input[type=search]:focus{outline:2px solid var(--accent);outline-offset:-1px}
  .chips{display:flex;gap:6px;flex-wrap:wrap}
  .chip{border:1px solid var(--line);background:var(--chip);color:var(--muted);
        border-radius:999px;padding:4px 11px;font-size:12.5px;cursor:pointer;user-select:none}
  .chip:hover{border-color:var(--accent)}
  .chip.on{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:600}

  .card{background:var(--card);border:1px solid var(--line);border-radius:12px;
        padding:15px 17px;margin-bottom:11px}
  .top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}
  .co{font-weight:660;font-size:16px;letter-spacing:-.01em}
  .meta{color:var(--muted);font-size:12.5px;margin-top:3px}
  .badges{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end;flex-shrink:0}
  .b{font-size:11.5px;padding:3px 9px;border-radius:999px;background:var(--chip);
     color:var(--muted);white-space:nowrap;font-weight:600}
  .b.tag{background:var(--accent);color:#fff}
  .b.pos{background:var(--posbg);color:var(--pos)}
  .b.neg{background:var(--negbg);color:var(--neg)}
  .b.neu{background:var(--neubg);color:var(--neu)}

  .head{margin:11px 0 0;font-size:13.5px;color:var(--muted)}
  .sum{margin:9px 0 0;font-size:14.5px}
  .nums{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}
  .num{background:var(--chip);border-radius:7px;padding:3px 9px;font-size:12.5px;
       font-variant-numeric:tabular-nums}
  .why{margin-top:9px;font-size:13px;color:var(--muted);border-left:2px solid var(--line);
       padding-left:10px}
  .links{margin-top:11px;display:flex;gap:14px;font-size:12.5px}
  .links a{color:var(--accent);text-decoration:none}
  .links a:hover{text-decoration:underline}
  .empty{text-align:center;color:var(--muted);padding:50px 0}
  footer{margin-top:26px;color:var(--muted);font-size:12px;text-align:center}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>Corporate Announcements</h1>
    <p id="sub"></p>
  </header>

  <div class="stats" id="stats"></div>

  <div class="controls">
    <input type="search" id="q" placeholder="Search company, ticker or text...">
    <div class="chips" id="chips"></div>
  </div>

  <div id="list"></div>
  <footer>Filed with NSE and BSE. Summaries generated by AI from the filed PDFs &mdash;
  always open the original before acting on anything.</footer>
</div>

<script>
const DATA = __DATA__;
const META = __META__;

document.getElementById('sub').textContent =
  META.window + '  ·  ' + META.total + ' filings scanned, ' +
  DATA.length + ' worth reading  ·  built ' + META.built;

const esc = s => (s||'').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

/* stat tiles */
const impactCount = k => DATA.filter(d => d.impact === k).length;
document.getElementById('stats').innerHTML = [
  ['Important', DATA.length],
  ['Positive', impactCount('Positive')],
  ['Negative', impactCount('Negative')],
  ['NSE', DATA.filter(d=>d.exchange.includes('NSE')).length],
  ['BSE', DATA.filter(d=>d.exchange.includes('BSE')).length],
].map(([k,v]) => '<div class="stat"><b>'+v+'</b><span>'+k+'</span></div>').join('');

/* filter chips, biggest groups first */
const tags = [...new Set(DATA.map(d=>d.tag))]
  .sort((a,b)=>DATA.filter(d=>d.tag===b).length - DATA.filter(d=>d.tag===a).length);
const nSum = DATA.filter(d=>d.summary).length;
let active = null;
document.getElementById('chips').innerHTML =
  '<div class="chip on" data-t="">All ' + DATA.length + '</div>' +
  (nSum ? '<div class="chip" data-t="@sum">With AI summary ' + nSum + '</div>' : '') +
  tags.map(t=>'<div class="chip" data-t="'+esc(t)+'">'+esc(t)+' '+
    DATA.filter(d=>d.tag===t).length+'</div>').join('');

document.getElementById('chips').addEventListener('click', e => {
  const c = e.target.closest('.chip'); if(!c) return;
  document.querySelectorAll('.chip').forEach(x=>x.classList.remove('on'));
  c.classList.add('on');
  active = c.dataset.t || null;
  render();
});
document.getElementById('q').addEventListener('input', render);

const cls = i => i==='Positive'?'pos' : i==='Negative'?'neg' : 'neu';

function card(d){
  const nums = (d.key_numbers||[]).map(n=>'<span class="num">'+esc(n)+'</span>').join('');
  return '<div class="card">'
    + '<div class="top"><div>'
      + '<div class="co">' + esc(d.company) + (d.ticker ? ' <span class="meta">'+esc(d.ticker)+'</span>' : '') + '</div>'
      + '<div class="meta">' + esc(d.exchange) + ' · ' + esc(d.category) + ' · ' + esc(d.time) + '</div>'
    + '</div><div class="badges">'
      + '<span class="b tag">' + esc(d.tag) + '</span>'
      + (d.impact ? '<span class="b '+cls(d.impact)+'">'+esc(d.impact)+'</span>' : '')
      + '<span class="b">' + d.score + '</span>'
    + '</div></div>'
    + '<div class="head">' + esc(d.headline) + '</div>'
    + (d.summary ? '<div class="sum">'+esc(d.summary)+'</div>' : '')
    + (nums ? '<div class="nums">'+nums+'</div>' : '')
    + (d.why_it_matters ? '<div class="why">'+esc(d.why_it_matters)+'</div>' : '')
    + '<div class="links">'
      + (d.pdf_url ? '<a href="'+esc(d.pdf_url)+'" target="_blank" rel="noopener">Open PDF</a>' : '')
      + (d.page_url ? '<a href="'+esc(d.page_url)+'" target="_blank" rel="noopener">Company page</a>' : '')
    + '</div></div>';
}

function render(){
  const q = document.getElementById('q').value.toLowerCase().trim();
  const rows = DATA.filter(d =>
    (!active || (active === '@sum' ? !!d.summary : d.tag === active)) &&
    (!q || (d.company+' '+d.ticker+' '+d.headline+' '+(d.summary||'')+' '+d.category)
             .toLowerCase().includes(q)));
  document.getElementById('list').innerHTML =
    rows.length ? rows.map(card).join('')
                : '<div class="empty">Nothing matches that filter.</div>';
}
render();
</script>
</body>
</html>
"""


# Models like to emit typographic characters that look odd on screen:
# narrow no-break space, non-breaking hyphen, fancy quotes.
TIDY = {
    " ": " ", " ": " ", " ": " ",
    "‑": "-", "–": "-", "—": " - ",
    "‘": "'", "’": "'", "“": '"', "”": '"',
}


def _tidy(v):
    if isinstance(v, str):
        for a, b in TIDY.items():
            v = v.replace(a, b)
        return v
    if isinstance(v, list):
        return [_tidy(x) for x in v]
    if isinstance(v, dict):
        return {k: _tidy(x) for k, x in v.items()}
    return v


def render(path, items, meta):
    items = _tidy(items)
    html = (TEMPLATE
            .replace("__DATA__", json.dumps(items, ensure_ascii=False))
            .replace("__META__", json.dumps(meta, ensure_ascii=False)))
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
